// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class concat_String_2 extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String string1;
	private final java.lang.String string2;

	public concat_String_2(
		IContext context,
		java.lang.String _string1,
		java.lang.String _string2
	)
	{
		super(context);
		this.string1 = _string1;
		this.string2 = _string2;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "concat_String_2";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
