// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package csv.actions;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.util.Date;
import java.util.Map.Entry;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.connectionbus.data.IDataRow;
import com.mendix.systemwideinterfaces.connectionbus.data.IDataTable;
import com.mendix.systemwideinterfaces.connectionbus.data.IDataTableSchema;
import com.mendix.systemwideinterfaces.connectionbus.requests.IParameterMap;
import com.mendix.systemwideinterfaces.connectionbus.requests.IRetrievalSchema;
import com.mendix.systemwideinterfaces.connectionbus.requests.types.IOQLTextGetRequest;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import com.opencsv.CSVWriter;
import csv.impl.CSV;
import oql.implementation.OQL;
import system.proxies.FileDocument;

public class ExportOQLToCSV extends CustomJavaAction<IMendixObject>
{
	private final java.lang.String statement;
	private final java.lang.Boolean exportHeaders;
	private final java.lang.String returnEntity;
	private final java.lang.Boolean removeNewLinesFromValues;
	private final java.lang.Boolean zipResult;
	private final java.lang.String separator;
	private final java.lang.String quoteCharacter;
	private final java.lang.String escapeCharacter;
	private final java.lang.String characterSet;

	public ExportOQLToCSV(
		IContext context,
		java.lang.String _statement,
		java.lang.Boolean _exportHeaders,
		java.lang.String _returnEntity,
		java.lang.Boolean _removeNewLinesFromValues,
		java.lang.Boolean _zipResult,
		java.lang.String _separator,
		java.lang.String _quoteCharacter,
		java.lang.String _escapeCharacter,
		java.lang.String _characterSet
	)
	{
		super(context);
		this.statement = _statement;
		this.exportHeaders = _exportHeaders;
		this.returnEntity = _returnEntity;
		this.removeNewLinesFromValues = _removeNewLinesFromValues;
		this.zipResult = _zipResult;
		this.separator = _separator;
		this.quoteCharacter = _quoteCharacter;
		this.escapeCharacter = _escapeCharacter;
		this.characterSet = _characterSet;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		final int PAGE_SIZE = 10000;
		
		ILogNode logger = CSV.getLogger();
		String suffix = ".csv";
		if (this.zipResult) {
			suffix += ".zip";
		}
		File tmpFile = File.createTempFile("Export", suffix);
		OutputStream os;
		FileOutputStream fos = new FileOutputStream(tmpFile);
		ZipOutputStream zos = null;
		if (zipResult) {
			zos = new ZipOutputStream(fos);
			zos.putNextEntry(new ZipEntry(tmpFile.getName().replaceAll(".zip", "")));
			os = zos;
		} else {
			os = fos;
		}
		
		CSVWriter writer = new CSVWriter(new OutputStreamWriter(os, (this.characterSet != null ? this.characterSet : "UTF-8")),
				separator == null ? CSVWriter.DEFAULT_SEPARATOR : separator.charAt(0),
				quoteCharacter == null ? CSVWriter.NO_QUOTE_CHARACTER : quoteCharacter.charAt(0),
				escapeCharacter == null ? CSVWriter.NO_ESCAPE_CHARACTER : escapeCharacter.charAt(0),
				System.lineSeparator());
		
		IMendixObject result = Core.instantiate(getContext(), this.returnEntity);
		
		logger.debug("Executing query");
		
		int offset = 0;
		while(true) {
			logger.debug("Executing query offset " + offset);
			IContext context = getContext().createSudoClone();
			IDataTable results = Core.retrieveOQLDataTable(context, buildRequest(offset, PAGE_SIZE));
			IDataTableSchema tableSchema = results.getSchema();
			if (offset == 0 && exportHeaders) {
				String[] headers = new String[tableSchema.getColumnCount()];
				for (int i = 0; i < tableSchema.getColumnCount(); i++) {
					headers[i] = tableSchema.getColumnSchema(i).getName();
				}
				writer.writeNext(headers);
			}
			
			for (IDataRow row : results.getRows()) {
				String[] values = new String[tableSchema.getColumnCount()];
				for (int i = 0; i < tableSchema.getColumnCount(); i++) {
					Object value = row.getValue(getContext(), i);
					if (value == null) {
						values[i] = "";
					} else {
						if (value instanceof Date) {
							values[i] = Long.toString(((Date) value).getTime()); // use timestamp to export for more precision than just seconds.
						} else if (value instanceof IMendixIdentifier) {
							values[i] = Long.toString(((IMendixIdentifier) value).toLong());
						} else {
							values[i] = value.toString();
						}
						if (this.removeNewLinesFromValues) {
							values[i] = values[i].replaceAll("\r", " ").replaceAll("\n", "");
						}
					}
				}
				writer.writeNext(values);
			}
			
			if (results.getRowCount() != PAGE_SIZE) {
				break;
			}
			offset += PAGE_SIZE;
		}
		writer.close();
		result.setValue(getContext(), FileDocument.MemberNames.Name.toString(), tmpFile.getName());
		Core.storeFileDocumentContent(getContext(), result, new FileInputStream(tmpFile));
		tmpFile.delete();
		OQL.resetParameters();
		
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExportOQLToCSV";
	}

	// BEGIN EXTRA CODE
	private IOQLTextGetRequest buildRequest(int offset, int pagesize) {
		IOQLTextGetRequest request = Core.createOQLTextGetRequest();
		request.setQuery(statement);
		IParameterMap parameterMap = request.createParameterMap();
		IRetrievalSchema schema = Core.createRetrievalSchema();
		schema.setAmount(pagesize);
		schema.setOffset(offset);
		request.setRetrievalSchema(schema);
		for (Entry<String, Object> entry : OQL.getNextParameters().entrySet()) {
			parameterMap.put(entry.getKey(), entry.getValue());
		}
		request.setParameters(parameterMap);
		return request;
	}
	// END EXTRA CODE
}
