// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package csv.actions;

import java.io.InputStreamReader;
import java.util.Map.Entry;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IDataType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.meta.IMetaObject;
import com.mendix.webui.CustomJavaAction;
import com.opencsv.CSVParser;
import com.opencsv.CSVParserBuilder;
import com.opencsv.CSVReader;
import com.opencsv.CSVReaderBuilder;
import com.opencsv.CSVWriter;
import csv.impl.CSV;

/**
 * This action will import a CSV.
 */
public class ImportCSV extends CustomJavaAction<IMendixObject>
{
	/** @deprecated use file.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __file;
	private final system.proxies.FileDocument file;
	private final java.lang.String microflow;
	private final IMendixObject microflowParameter;
	private final java.lang.Boolean useSystemContext;
	private final java.lang.String separator;
	private final java.lang.String quoteCharacter;
	private final java.lang.String escapeCharacter;
	private final java.lang.Long skipLines;
	private final java.lang.String returnEntity;
	private final java.lang.String characterSet;

	public ImportCSV(
		IContext context,
		IMendixObject _file,
		java.lang.String _microflow,
		IMendixObject _microflowParameter,
		java.lang.Boolean _useSystemContext,
		java.lang.String _separator,
		java.lang.String _quoteCharacter,
		java.lang.String _escapeCharacter,
		java.lang.Long _skipLines,
		java.lang.String _returnEntity,
		java.lang.String _characterSet
	)
	{
		super(context);
		this.__file = _file;
		this.file = _file == null ? null : system.proxies.FileDocument.initialize(getContext(), _file);
		this.microflow = _microflow;
		this.microflowParameter = _microflowParameter;
		this.useSystemContext = _useSystemContext;
		this.separator = _separator;
		this.quoteCharacter = _quoteCharacter;
		this.escapeCharacter = _escapeCharacter;
		this.skipLines = _skipLines;
		this.returnEntity = _returnEntity;
		this.characterSet = _characterSet;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		ILogNode logger = CSV.getLogger();
		
		logger.debug("Opening CSV file..");
		
		CSVParserBuilder parserBuilder = new CSVParserBuilder()
				.withSeparator(this.separator == null ? CSVWriter.DEFAULT_SEPARATOR : this.separator.charAt(0))
				.withQuoteChar(this.quoteCharacter == null ? CSVWriter.NO_QUOTE_CHARACTER : this.quoteCharacter.charAt(0))
				.withEscapeChar(this.escapeCharacter == null ? CSVWriter.NO_ESCAPE_CHARACTER : this.escapeCharacter.charAt(0));
		
		CSVParser parser = parserBuilder.build();
		
		CSVReader reader = new CSVReaderBuilder(
					new InputStreamReader(Core.getFileDocumentContent(getContext(), this.file.getMendixObject()), 
							(this.characterSet != null ? this.characterSet : "UTF-8")
					)
				)
				.withSkipLines((int) skipLines.intValue())
				.withCSVParser(parser)
				.build();
		
		logger.debug("CSV file opened..");
		
		IContext context = getContext();
		if (useSystemContext) {
			context = Core.createSystemContext();
		}
		Object result = null;

		try {
			context.getData().put(CSV.CONTEXT_READER_OBJ, reader);
			if (this.microflowParameter != null) {
				String argument = null;
				for(Entry<String, IDataType> entry : Core.getInputParameters(microflow).entrySet()) {
					IDataType dataType = entry.getValue();
					if (dataType.isMendixObject()) {
						if (dataType.getObjectType().equals(microflowParameter.getType())) {
							argument = entry.getKey();
							break;
						}
 						
						IMetaObject metaObject = Core.getMetaObject(dataType.getObjectType());
						if (microflowParameter.getMetaObject().isSubClassOf(metaObject)) {
							argument = entry.getKey();
							break;
						}
					}
				}
					
				if (argument == null) {
					throw new CoreException("No suitable argument could be found in microflow " + microflow + " for " + microflowParameter.getType());
				}
				result = Core.microflowCall(microflow).withParam(argument, microflowParameter).execute(context);
			} else {
				result = Core.microflowCall(this.microflow).execute(context);
			}
			logger.debug("Sucessfully imported CSV file.");
			
			if (useSystemContext) {
				while (context.isInTransaction())
					context.endTransaction();
			}
			
		} finally {
			logger.debug("Closing CSV file..");
			reader.close();
		}
		
		
		if (result != null && result instanceof IMendixObject) {
			return (IMendixObject) result;
		} else {		
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ImportCSV";
	}

	// BEGIN EXTRA CODE

	// END EXTRA CODE
}
